### ISSUE TITLE
SwipeButton component won't work as expected on android

### ISSUE THREAD

**Issue by alexanderwassbjer** [arelstone/react-native-swipe-button#10]
Hi,

The swipe button component do not work as expected on android. Can't drag the trigger the onComplete event.

Here is how I use the component:
`<SwipeButton
                  onComplete={() => useTestFunction()}
                  title="Test"
                  borderRadius={50}
                  goBackToStart={false}
                />`

**Comment by arelstone** [comment]
@alexanderwassbjer I am sorry to see that your are having problems with this.

Did you find a solution? In that case a PR would be very much appriciated

**Comment by ibearth2025** [comment]
Hello any solution yet ?

**Comment by alexanderwassbjer** [comment]
I ended up not using the component. Thanks anyway.
