### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by samshahbazi** [arelstone/react-native-swipe-button#6]
you just wrote the properties but you did not mention how to use this package...

**Comment by arelstone** [comment]
@samshahbazi As far as I remember an example directory is provided with a very basic example. https://github.com/arelstone/react-native-swipe-button/blob/master/example/Example.tsx

```tsx
import SwipeButton from '../src/SwipeButton';
// ...
<SwipeButton
  Icon={<Text>X</Text>}
  onComplete={() => Alert.alert('Completed')}
  title="Swipe to complete"
/>
```
